import Head from "next/head";
import Hero from "../components/Hero";

export default function Home({ heading, message }) {
  return (
    <>
      <div>
        <Head>
          <title>Portfolio App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero heading="Erika Pineda" message="Full-Stack Web Developer" />
      </div>
    </>
  );
}
