import Head from "next/head";
import Hero from "../components/Hero";
import About from "../components/About";
import Portfolio from "../components/Portfolio";
import Contact from "../components/Contact";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/codebracket.png" />
        </Head>
        <Hero heading="Erika Pineda" message="Full-Stack Web Developer" />
        <About />
        <Skills />
        <Portfolio />
        <Contact />
      </div>
    </>
  );
}
